local lights = {}

for _, part in pairs(script.Parent:GetChildren()) do
	if part.Name == string.match(part.Name, '^Light.*$') then
		lights[tonumber(string.match(part.Name, "%d+"))] = part
	end
end

wait(5)

spawn(function()
	while true do
		for _, light in ipairs(lights) do
			light.Material = Enum.Material.SmoothPlastic
			light.Light.Brightness = 0
			if light:FindFirstChild("Main") ~= nil then
				light.Main.Enabled = false
			end
			wait()
		end
	end
end)

wait(3.2)

spawn(function()
	while true do
		for _, light in ipairs(lights) do
			light.Material = Enum.Material.Neon
			light.Light.Brightness = 2
			if light:FindFirstChild("Main") ~= nil then
				light.Main.Enabled = true
			end
			wait()
		end
	end
end)

--todo make lights toggleable
