local dataLink = script["Data Link"].Value

local center = script.Parent.CFrame
local knob = script.Parent
local TweenService = game:GetService("TweenService")
local tweeningInfo = TweenInfo.new(.3, Enum.EasingStyle.Linear, Enum.EasingDirection.In, 0, false, 0)
local properties = { CFrame = CFrame.new(-2.91222191, 7.07171202, 50.5812302, -0.500011086, -0.288156807, -0.816672921, 0, 0.943019509, -0.332737267, 0.86601913, -0.166372299, -0.471520185); }
local tweenActivate = TweenService:Create(knob, tweeningInfo, properties)

local tweeningInfo = TweenInfo.new(.3, Enum.EasingStyle.Linear, Enum.EasingDirection.In, 0, false, 0)
local properties = { CFrame = CFrame.new(-2.91222191, 7.07171202, 50.5812302, 0.816672802, -0.288157552, -0.500010788, 0.332737923, 0.943019331, -2.67835475e-07, 0.471519887, -0.166372329, 0.866019309); }
local tweenDeactivate = TweenService:Create(knob, tweeningInfo, properties)

function leftClick()
	if dataLink.isTemporalLocatorRelative.Value == false then
		tweenActivate:Play()
		dataLink.isTemporalLocatorRelative.Value = true

	elseif dataLink.isTemporalLocatorRelative.Value then
		tweenDeactivate:Play()
		dataLink.isTemporalLocatorRelative.Value = false
	end

	script.Parent.Sound.Playing = true
end


script.Parent.Use.MouseClick:connect(leftClick)
