function onClicked()

wait(0.05)

if script.Parent.Main.Pulled.Value == true then

script.Parent.LED1.Material = Enum.Material.SmoothPlastic
wait(0.05)
script.Parent.LED2.Material = Enum.Material.SmoothPlastic
wait(0.05)
script.Parent.LED3.Material = Enum.Material.SmoothPlastic
wait(0.05)
script.Parent.LED4.Material = Enum.Material.SmoothPlastic
wait(0.05)
script.Parent.LED5.Material = Enum.Material.SmoothPlastic
wait(0.05)
script.Parent.LED6.Material = Enum.Material.SmoothPlastic
wait(0.05)
script.Parent.LED7.Material = Enum.Material.SmoothPlastic
wait(0.05)

else

script.Parent.LED7.Material = Enum.Material.Neon
wait(0.05)
script.Parent.LED6.Material = Enum.Material.Neon
wait(0.05)
script.Parent.LED5.Material = Enum.Material.Neon
wait(0.05)
script.Parent.LED4.Material = Enum.Material.Neon
wait(0.05)
script.Parent.LED3.Material = Enum.Material.Neon
wait(0.05)
script.Parent.LED2.Material = Enum.Material.Neon
wait(0.05)
script.Parent.LED1.Material = Enum.Material.Neon
wait(0.05)

end
end

script.Parent.Main.Use.MouseClick:connect(onClicked)