game = script.Parent

function rotateMod(mod, center, rotation)
	local parts = {}
	local function scan(parent)
		for _, obj in pairs(parent:GetChildren()) do
			if (obj:IsA("BasePart")) then
				table.insert(parts, obj)
			end
			scan(obj)
		end
	end

	scan(mod)
	for _, part in pairs(parts) do
		part.CFrame = (center * rotation * (center:inverse() * part.CFrame))
	end
end

function onClicked()

	if script.Parent.Value.Value == false then
		script.Parent.Value.Value = true
		local mod = game
		local step = 1
		for i = 0, 26, step do
			rotateMod(mod, mod:GetModelCFrame(), CFrame.Angles(-0.05, 0, 0))
			wait()
		end

	else

		script.Parent.Value.Value = false
		local mod = game
		local step = 1
		for i = 0, 26, step do
			rotateMod(mod, mod:GetModelCFrame(), CFrame.Angles(0.05, 0, 0))
			wait()
		end
	end
end

script.Parent.ClickDetector.MouseClick:connect(onClicked)


