function Light()

	script.Parent.MainPhase.Disabled = true
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1

	wait(0.3) -- Edit this with every increasing light array

	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 2
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.6
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.3
	script.Parent.Light2.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 1.4
	script.Parent.Light2.Light.Brightness = 2
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.75
	script.Parent.Light2.Transparency = 0.6
	script.Parent.Light3.Transparency = 1
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.6
	script.Parent.Light2.Main.Lit.ImageTransparency = 0.3
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 0.8
	script.Parent.Light2.Light.Brightness = 1.4
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 0.9
	script.Parent.Light2.Transparency = 0.75
	script.Parent.Light3.Transparency = 0.6
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.9
	script.Parent.Light2.Main.Lit.ImageTransparency = 0.6
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.3
	script.Parent.Light1.Light.Brightness = 0.2
	script.Parent.Light2.Light.Brightness = 0.8
	script.Parent.Light3.Light.Brightness = 1.4
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 0.9
	script.Parent.Light3.Transparency = 0.75
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 0.9
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.6
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0.2
	script.Parent.Light3.Light.Brightness = 0.8
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 0.9
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.9
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0.2
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(0.6)

	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 2
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.6
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.3
	script.Parent.Light2.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 1.4
	script.Parent.Light2.Light.Brightness = 2
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.75
	script.Parent.Light2.Transparency = 0.6
	script.Parent.Light3.Transparency = 1
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.6
	script.Parent.Light2.Main.Lit.ImageTransparency = 0.3
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 0.8
	script.Parent.Light2.Light.Brightness = 1.4
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 0.9
	script.Parent.Light2.Transparency = 0.75
	script.Parent.Light3.Transparency = 0.6
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.9
	script.Parent.Light2.Main.Lit.ImageTransparency = 0.6
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.3
	script.Parent.Light1.Light.Brightness = 0.2
	script.Parent.Light2.Light.Brightness = 0.8
	script.Parent.Light3.Light.Brightness = 1.4
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 0.9
	script.Parent.Light3.Transparency = 0.75
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 0.9
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.6
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0.2
	script.Parent.Light3.Light.Brightness = 0.8
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 0.9
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.9
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0.2
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(0.6)

	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 2
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.6
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.3
	script.Parent.Light2.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 1.4
	script.Parent.Light2.Light.Brightness = 2
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.75
	script.Parent.Light2.Transparency = 0.6
	script.Parent.Light3.Transparency = 1
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.6
	script.Parent.Light2.Main.Lit.ImageTransparency = 0.3
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 0.8
	script.Parent.Light2.Light.Brightness = 1.4
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 0.9
	script.Parent.Light2.Transparency = 0.75
	script.Parent.Light3.Transparency = 0.6
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.9
	script.Parent.Light2.Main.Lit.ImageTransparency = 0.6
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.3
	script.Parent.Light1.Light.Brightness = 0.2
	script.Parent.Light2.Light.Brightness = 0.8
	script.Parent.Light3.Light.Brightness = 1.4
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 0.9
	script.Parent.Light3.Transparency = 0.75
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 0.9
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.6
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0.2
	script.Parent.Light3.Light.Brightness = 0.8
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 0.9
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.9
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0.2
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(0.6)

	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 2
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.6
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.3
	script.Parent.Light2.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 1.4
	script.Parent.Light2.Light.Brightness = 2
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.75
	script.Parent.Light2.Transparency = 0.6
	script.Parent.Light3.Transparency = 1
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.6
	script.Parent.Light2.Main.Lit.ImageTransparency = 0.3
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 0.8
	script.Parent.Light2.Light.Brightness = 1.4
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 0.9
	script.Parent.Light2.Transparency = 0.75
	script.Parent.Light3.Transparency = 0.6
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.9
	script.Parent.Light2.Main.Lit.ImageTransparency = 0.6
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.3
	script.Parent.Light1.Light.Brightness = 0.2
	script.Parent.Light2.Light.Brightness = 0.8
	script.Parent.Light3.Light.Brightness = 1.4
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 0.9
	script.Parent.Light3.Transparency = 0.75
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 0.9
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.6
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0.2
	script.Parent.Light3.Light.Brightness = 0.8
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 0.9
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.9
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0.2
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(0.005)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light2.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light2.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 1
	script.Parent.Light2.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(0.6)

	if game.Workspace.Glass.Fly.Value == true then

		script.Parent.MainPhase.Disabled = false

	else

		wait(2.1)

		script.Parent.Light1.Main.Lit.ImageTransparency = 0
		script.Parent.Light2.Main.Lit.ImageTransparency = 0
		script.Parent.Light3.Main.Lit.ImageTransparency = 0
		script.Parent.Light1.Light.Brightness = 2
		script.Parent.Light2.Light.Brightness = 2
		script.Parent.Light3.Light.Brightness = 2
		script.Parent.Light1.Transparency = 0.6
		script.Parent.Light2.Transparency = 0
		script.Parent.Light3.Transparency = 0.6
	end
end

game.Workspace.Glass.Fly.Changed:connect(Light)