wait()

while true do

	script.Parent.Light1.Main.Lit.ImageTransparency = 0.75
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 0.5
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.95
	script.Parent.Light3.Transparency = 1
	wait(0.025)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.5
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 1
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.8
	script.Parent.Light3.Transparency = 1
	wait(0.025)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.25
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 1.5
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.65
	script.Parent.Light3.Transparency = 1
	wait(0.025)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 0.6
	script.Parent.Light3.Light.Brightness = 0
	wait(0.125)

	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 2
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.6
	script.Parent.Light3.Transparency = 1
	wait(0.025)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 2
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.6
	script.Parent.Light3.Transparency = 1
	wait(0.025)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 2
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.6
	script.Parent.Light3.Transparency = 1
	wait(0.025)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 2
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 0.6
	script.Parent.Light3.Transparency = 1
	wait(0.125)

	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.75
	script.Parent.Light1.Light.Brightness = 2
	script.Parent.Light3.Light.Brightness = 0.5
	script.Parent.Light1.Transparency = 0.6
	script.Parent.Light3.Transparency = 0.95
	wait(0.025)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.5
	script.Parent.Light1.Light.Brightness = 2
	script.Parent.Light3.Light.Brightness = 1
	script.Parent.Light1.Transparency = 0.6
	script.Parent.Light3.Transparency = 0.8
	wait(0.025)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.25
	script.Parent.Light1.Light.Brightness = 2
	script.Parent.Light3.Light.Brightness = 1.5
	script.Parent.Light1.Transparency = 0.6
	script.Parent.Light3.Transparency = 0.65
	wait(0.025)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 2
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 0.6
	script.Parent.Light3.Transparency = 0.6
	wait(0.125)

	script.Parent.Light1.Main.Lit.ImageTransparency = 0.25
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 1.5
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 0.65
	script.Parent.Light3.Transparency = 0.6
	wait(0.05)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.5
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 1
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 0.8
	script.Parent.Light3.Transparency = 0.6
	wait(0.05)
	script.Parent.Light1.Main.Lit.ImageTransparency = 0.75
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 0.5
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 0.95
	script.Parent.Light3.Transparency = 0.6
	wait(0.05)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 1
	script.Parent.Light3.Transparency = 0.6
	wait(0.05)

	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 1
	script.Parent.Light3.Transparency = 0.6
	wait(0.05)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 1
	script.Parent.Light3.Transparency = 0.6
	wait(0.05)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 1
	script.Parent.Light3.Transparency = 0.6
	wait(0.05)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 0
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 2
	script.Parent.Light1.Transparency = 1
	script.Parent.Light3.Transparency = 0.6
	wait(0.05)

	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.25
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 1.5
	script.Parent.Light1.Transparency = 1
	script.Parent.Light3.Transparency = 0.65
	wait(0.05)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.5
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 1
	script.Parent.Light1.Transparency = 1
	script.Parent.Light3.Transparency = 0.8
	wait(0.05)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 0.75
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0.5
	script.Parent.Light1.Transparency = 1
	script.Parent.Light3.Transparency = 0.95
	wait(0.05)
	script.Parent.Light1.Main.Lit.ImageTransparency = 1
	script.Parent.Light3.Main.Lit.ImageTransparency = 1
	script.Parent.Light1.Light.Brightness = 0
	script.Parent.Light3.Light.Brightness = 0
	script.Parent.Light1.Transparency = 1
	script.Parent.Light3.Transparency = 1
	wait(2.45)
end