function Pulled()

	script.Parent.Use.MaxActivationDistance = 0
	wait(0.1)

	if script.Parent.Throttled.Value == true then

		if game.Workspace.Glass.Fly.Value == false then
			game.Workspace.Glass.Fly.Value = true
		end

		script.Parent.Parent.LEDs.BulbA.Material = Enum.Material.Neon
		script.Parent.Parent.LEDs.BulbB.Material = Enum.Material.Neon
		script.Parent.Parent.LEDs.SmallLED1.Material = Enum.Material.SmoothPlastic
		script.Parent.Parent.LEDs.SmallLED2.Material = Enum.Material.SmoothPlastic
		script.Parent.Parent.LEDs.SmallLED3.Material = Enum.Material.SmoothPlastic
		script.Parent.Parent.LEDs.SmallLED4.Material = Enum.Material.SmoothPlastic
		script.Parent.Parent.LEDs.SmallLED5.Material = Enum.Material.SmoothPlastic

	else

		script.Parent.Parent.LEDs.BulbA.Material = Enum.Material.SmoothPlastic
		script.Parent.Parent.LEDs.BulbB.Material = Enum.Material.SmoothPlastic
		script.Parent.Parent.LEDs.SmallLED1.Material = Enum.Material.Neon
		script.Parent.Parent.LEDs.SmallLED2.Material = Enum.Material.Neon
		script.Parent.Parent.LEDs.SmallLED3.Material = Enum.Material.Neon
		script.Parent.Parent.LEDs.SmallLED4.Material = Enum.Material.Neon
		script.Parent.Parent.LEDs.SmallLED5.Material = Enum.Material.Neon

		if game.Workspace.Glass.Fly.Value == true then
			game.Workspace.Glass.Landing:Play()
			wait(14)
		end
		if game.Workspace.Glass.Fly.Value == true then
			game.Workspace.Glass.Fly.Value = false
			wait(6)
		end
	end
	script.Parent.Use.MaxActivationDistance = 10
end

script.Parent.Use.MouseClick:connect(Pulled)