function Up()

	script.Parent.Holding.Value = true

	wait(0.2)
	if script.Parent.Holding.Value == true then
		script.Parent.Handle.Sound.Volume = 0.2
		script.Parent.CrystalUp.Material = Enum.Material.Neon
		script.Parent.CrystalDown.Material = Enum.Material.Neon

	else

		if script.Parent.Extended.Value == false then
			script.Parent.Extended.Value = true
			script.Parent.Handle.Extend:Play()
			script.Parent.Handle.Sound.Pitch = 1.1
			script.Parent.CrystalDown.Transparency = 1
			script.Parent.CrystalUp.Transparency = 0
			script.Parent.SilverClosed.Transparency = 1
			script.Parent.SilverOpen.Transparency = 0

		else

			script.Parent.Extended.Value = false
			script.Parent.Handle.Sound.Pitch = 1
			script.Parent.CrystalDown.Transparency = 0
			script.Parent.CrystalUp.Transparency = 1
			script.Parent.SilverClosed.Transparency = 0
			script.Parent.SilverOpen.Transparency = 1
		end
	end
end


function Down()

	script.Parent.Holding.Value = false
	script.Parent.Handle.Sound.Volume = 0
	script.Parent.CrystalUp.Material = Enum.Material.SmoothPlastic
	script.Parent.CrystalDown.Material = Enum.Material.SmoothPlastic
end


script.Parent.Activated:connect(Up)
script.Parent.Deactivated:connect(Down)