local dataLink = script["Data Link"].Value
local button = script.Parent.Parent.SearchButton


script.Parent.Use.MouseClick:Connect(function()
	if dataLink.isDataSingleSearchActive.Value == false then
		button.Position = Vector3.new(button.Position.X + 0.02, button.Position.Y - 0.065, button.Position.Z - 0.011)
		dataLink.isDataSingleSearchActive.Value = true
		script.Parent.Parent.Parent.LED.Bulb.Color = Color3.fromRGB(0, 255, 0)

	elseif dataLink.isDataSingleSearchActive.Value then
		button.Position = Vector3.new(button.Position.X - 0.02, button.Position.Y + 0.065, button.Position.Z + 0.011)
		dataLink.isDataSingleSearchActive.Value = false
		script.Parent.Parent.Parent.LED.Bulb.Color = Color3.fromRGB(196, 40, 28)
		dataLink.isDataScanningForTardis.Value = false
		dataLink.isDataScanningForMisc.Value = false
		dataLink.isDataScanningForSonic.Value = false
	end
end)
