throttle = script.Parent

function rotateMod(mod, center, rotation)
	local parts = {}
	local function scan(parent)
		for _, obj in pairs(parent:GetChildren()) do
			if (obj:IsA("BasePart")) then
				table.insert(parts, obj)
			end
			scan(obj)
		end
	end

	scan(mod)
	for _, part in pairs(parts) do
		part.CFrame = (center * rotation * (center:inverse() * part.CFrame))
	end
end

function Pulled()

	if script.Parent.Throttled.Value == false then
		script.Parent.Throttled.Value = true
		script.Parent.Leverage.Sound1:Play()
		local mod = throttle
		local step = 1
		for i = 0, 8, step do
			rotateMod(mod, mod:GetModelCFrame(), CFrame.Angles(0, -0.3, 0))
			wait()
		end

	else

		script.Parent.Throttled.Value = false
		script.Parent.Leverage.Sound2:Play()
		local mod = throttle
		local step = 1
		for i = 0, 8, step do
			rotateMod(mod, mod:GetModelCFrame(), CFrame.Angles(0, 0.3, 0))
			wait()
		end
	end
end

script.Parent.Use.MouseClick:connect(Pulled)