function onClicked()

	wait(0.1)

	if script.Parent.Up.Value == false then
		script.Parent.Up.Value = true
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, 0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, 0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, 0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, 0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, 0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, 0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, 0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, 0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, 0.05)
		wait(0.02)
		script.Parent.Sound:Play()

	else

		script.Parent.Up.Value = false
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, -0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, -0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, -0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, -0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, -0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, -0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, -0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, -0.05)
		wait(0.02)
		script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0, -0.05)
		wait(0.02)
		script.Parent.Sound:Play()
	end
end

script.Parent.Use.MouseClick:connect(onClicked)

