lever = script.Parent

function rotateMod(mod, center, rotation)
	local parts = {}
	local function scan(parent)
		for _, obj in pairs(parent:GetChildren()) do
			if (obj:IsA("BasePart")) then
				table.insert(parts, obj)
			end
			scan(obj)
		end
	end

	scan(mod)
	for _, part in pairs(parts) do
		part.CFrame = (center * rotation * (center:inverse() * part.CFrame))
	end
end

function Used()

	if script.Parent.LeverUp.Value == false then
		script.Parent.LeverUp.Value = true
		local mod = lever
		local step = 1
		for i = 0, 5, step do
			rotateMod(mod, mod:GetModelCFrame(), CFrame.Angles(0, 0, -0.3))
			wait()
		end

	else

		script.Parent.LeverUp.Value = false
		local mod = lever
		local step = 1
		for i = 0, 5, step do
			rotateMod(mod, mod:GetModelCFrame(), CFrame.Angles(0, 0, 0.3))
			wait()
		end
	end
end

script.Parent.Use.MouseClick:connect(Used)