function Light()
	wait(0.2)
	if game.Workspace.Glass.Fly.Value == true then

		script.Parent.A.Transparency = 0.4
		script.Parent.B.Transparency = 0.4
		script.Parent.C.Transparency = 0.4
		script.Parent.D.Transparency = 0.4
		script.Parent.E.Transparency = 0.4
		script.Parent.F.Transparency = 0.4
		script.Parent.G.Transparency = 0.4
		script.Parent.H.Transparency = 0.4
		script.Parent.I.Transparency = 0.4
		script.Parent.J.Transparency = 0.4
		script.Parent.K.Transparency = 0.4
		script.Parent.L.Transparency = 0.4
		script.Parent.M.Transparency = 0.4
		script.Parent.N.Transparency = 0.4
		wait()
		script.Parent.Phase.Disabled = false

	else

		wait(6)
		script.Parent.Phase.Disabled = true
		wait()
		script.Parent.A.Transparency = 0
		script.Parent.B.Transparency = 0
		script.Parent.C.Transparency = 0
		script.Parent.D.Transparency = 0
		script.Parent.E.Transparency = 0
		script.Parent.F.Transparency = 0
		script.Parent.G.Transparency = 0
		script.Parent.H.Transparency = 0
		script.Parent.I.Transparency = 0
		script.Parent.J.Transparency = 0
		script.Parent.K.Transparency = 0
		script.Parent.L.Transparency = 0
		script.Parent.M.Transparency = 0
		script.Parent.N.Transparency = 0
	end
end

game.Workspace.Glass.Fly.Changed:connect(Light)