function Move()

	wait(0.5)

	if game.Workspace.Glass.Fly.Value == true then
		while game.Workspace.Glass.Fly.Value == true do

			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.04, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.03, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.02, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, 0.01, 0)
			wait(1)

			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.05, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.04, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.03, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.02, 0)
			wait(0.01)
			script.Parent.CFrame = script.Parent.CFrame * CFrame.new(0, -0.01, 0)
			wait(0.2)
		end
	end
end

game.Workspace.Glass.Fly.Changed:connect(Move)