function Power()
	wait(0.1)
	if game.Workspace.Glass.TrimOff.Value == true then
		script.Parent.LightsA.LEDs.Enabled = false
		script.Parent.LightsB.LEDs.Enabled = false
	else
		script.Parent.LightsA.LEDs.Enabled = true
		script.Parent.LightsB.LEDs.Enabled = true
	end
end


function Shrink()
	if game.Workspace.Glass.Shrink.Value == true then
		wait(3.5)
		local n = math.random(1, 3)
		if n == 3 then
			script.Parent.LightsA.LEDs.Enabled = false
			script.Parent.LightsB.LEDs.Enabled = false
		end
	else
		script.Parent.LightsA.LEDs.Enabled = true
		script.Parent.LightsB.LEDs.Enabled = true
	end
end

game.Workspace.Glass.TrimOff.Changed:connect(Power)
game.Workspace.Glass.Shrink.Changed:connect(Shrink)